name: WCAG tests

on: push

jobs:
  call_WCAG_test:
    uses:  yext/answers-headless/.github/workflows/wcag_test_reuse.yml@dev/test-reusable-workflows
    with:
      node_version: '14.x'
      build_script: 'npm run build'
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
